export const list = [{
    id: 1,
    first_name: 'Gwenora',
    last_name: 'Hylands',
    email: 'ghylands0@arizona.edu',
    gender: 'Female'
  }, {
    id: 2,
    first_name: 'Haleigh',
    last_name: 'Nicholes',
    email: 'hnicholes1@live.com',
    gender: 'Female'
  }, {
    id: 3,
    first_name: 'Jacobo',
    last_name: 'Kensall',
    email: 'jkensall2@feedburner.com',
    gender: 'Male'
  }, {
    id: 4,
    first_name: 'Gates',
    last_name: 'Bernucci',
    email: 'gbernucci3@aboutads.info',
    gender: 'Female'
  }, {
    id: 5,
    first_name: 'Conney',
    last_name: 'Willsmore',
    email: 'cwillsmore4@slideshare.net',
    gender: 'Male'
  }, {
    id: 6,
    first_name: 'Elladine',
    last_name: 'Presswell',
    email: 'epresswell5@bloglovin.com',
    gender: 'Female'
  }, {
    id: 7,
    first_name: 'Jacklyn',
    last_name: 'Brave',
    email: 'jbrave6@wikimedia.org',
    gender: 'Female'
  }, {
    id: 8,
    first_name: 'Valenka',
    last_name: 'Vasyutin',
    email: 'vvasyutin7@redcross.org',
    gender: 'Female'
  }, {
    id: 9,
    first_name: 'Jody',
    last_name: 'McNerlin',
    email: 'jmcnerlin8@domainmarket.com',
    gender: 'Male'
  }, {
    id: 10,
    first_name: 'Griffie',
    last_name: 'Monery',
    email: 'gmonery9@yandex.ru',
    gender: 'Male'
  }]